CREATE TABLE IF NOT EXISTS `roa_profession_daily_quests` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `quest_id` int(10) unsigned NOT NULL COMMENT 'Quest ID from quest_template',
  `quest_name` varchar(255) NOT NULL COMMENT 'Display name of the quest',
  `description` text NOT NULL COMMENT 'Quest description shown in UI',
  `level_required` int(3) unsigned NOT NULL DEFAULT '1' COMMENT 'Minimum level required',
  `level_max` int(3) unsigned NOT NULL DEFAULT '80' COMMENT 'Maximum level allowed',
  `icon` varchar(255) NOT NULL DEFAULT 'Interface\\Icons\\INV_Misc_QuestionMark' COMMENT 'Quest icon path',
  `background_image` varchar(255) DEFAULT NULL COMMENT 'Optional background image path',
  `profession_type` varchar(50) DEFAULT NULL COMMENT 'Profession type (e.g., Mining, Herbalism, etc.)',
  `sort_order` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Order in which quests appear',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT 'Whether quest is active (1) or disabled (0)',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_quest_id` (`quest_id`),
  KEY `idx_active_sort` (`active`, `sort_order`),
  KEY `idx_profession` (`profession_type`),
  KEY `idx_level_range` (`level_required`, `level_max`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Daily profession quests configuration';